version: 2
updates:
- package-ecosystem: npm
  directory: "/packages/chakra-ui"
  schedule:
    interval: daily
    time: "00:00"
  open-pull-requests-limit: 10
  target-branch: master
  labels:
  - "Type: Dependency"
  ignore:
  - dependency-name: react-spring
    versions:
    - 9.0.0
    - 9.0.1
    - 9.1.0
    - 9.1.1
  - dependency-name: "@reach/auto-id"
    versions:
    - 0.13.0
    - 0.13.2
    - 0.14.0
  - dependency-name: "@types/styled-system"
    versions:
    - 5.1.10
  commit-message:
    prefix: chore
    include: scope
